// Mock for libtransmissionbtm_napi.so
// N-API native module is unavailable in Node.js vitest runtime.
// All methods return sensible defaults for unit testing.

export default {
  getVersion(): string { return '0.1.0-mock'; },
  sessionStart(): BigInt { return BigInt(0); },
  sessionStop(): void {},
  sessionSuspend(): void {},
  hasDownloadingTorrents(): boolean { return false; },
  listTorrentNames(): string[] { return []; },
  getEncryptionMode(): number { return 1; },
  transmissionVersion(): string { return '4.1.0-mock'; },
  torrentAdd(): number { return 0; },
  torrentRemove(): void {},
  torrentStart(): void {},
  torrentStop(): void {},
  torrentVerify(): void {},
  torrentListFilesFromFile(): string[] { return []; },
  torrentListFiles(): string[] { return []; },
  torrentFindByHash(): number { return -1; },
  torrentGetName(): string { return ''; },
  torrentGetHash(_sessionId: number, _torrentId: number, _buf: ArrayBuffer): void {},
  torrentGetPieceHash(_sessionId: number, _torrentId: number, _pieceIndex: BigInt, _buf: ArrayBuffer): void {},
  torrentSetPiecesHiPri(): void {},
  torrentFindFile(): string { return ''; },
  torrentGetFileName(): string { return ''; },
  torrentGetFileStat(): ArrayBuffer { return new ArrayBuffer(0); },
  torrentGetPiece(_sessionId: number, _torrentId: number, _pieceIndex: BigInt, _dst: ArrayBuffer, _off: number, _len: number): void {},
  torrentStatBrief(): ArrayBuffer { return new ArrayBuffer(0); },
  torrentGetError(): string { return ''; },
  torrentSetDnd(): void {},
  torrentSetLocation(): void {},
  hashLength(): number { return 20; },
  hashBytesToString(): string { return ''; },
  hashStringToBytes(): ArrayBuffer { return new ArrayBuffer(0); },
  hashGetTorrentHash(): ArrayBuffer { return new ArrayBuffer(0); },
  curlDownload(): void {},
  semCreate(): BigInt { return BigInt(0); },
  semDestroy(): void {},
  semPost(): void {},
  envUnset(): void {},
  envSet(): void {},
  nativeToArktsInit(): void {},
  nativeToArktsRelease(): void {},
  stdRedirect(): void {},
};
